/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_eigen;


/**
 *
 * @author johan
 */
public class kunden_daten extends javax.swing.JFrame {

    /**
     * Creates new form kunden_daten
     */
    public kunden_daten() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonregistrierung = new javax.swing.JButton();
        jButtonzimmer = new javax.swing.JButton();
        jButtonkunde = new javax.swing.JButton();
        jButtonbuchung = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jkundennachname = new javax.swing.JTextField();
        jkundenvorname = new javax.swing.JTextField();
        jkundenwohnort = new javax.swing.JTextField();
        jkundenpostleitzahl = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jkundenvornam1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButtonloeschen = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(222, 238, 248));
        jPanel1.setEnabled(false);

        jPanel2.setBackground(new java.awt.Color(91, 142, 206));

        jTextArea1.setBackground(new java.awt.Color(91, 142, 206));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Hier könnte schon \nbald ihre \nFunktionalität \nentstehen...");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );

        jPanel4.setBackground(new java.awt.Color(91, 142, 206));

        jLabel1.setBackground(new java.awt.Color(222, 238, 206));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 238, 248));
        jLabel1.setText("In welchem Zimmer möchte der Kunde eingebucht werden? ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(91, 142, 206));

        jButtonregistrierung.setBackground(new java.awt.Color(91, 142, 206));
        jButtonregistrierung.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButtonregistrierung.setForeground(new java.awt.Color(222, 238, 248));
        jButtonregistrierung.setText("Registrierung");
        jButtonregistrierung.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jButtonregistrierung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregistrierungActionPerformed(evt);
            }
        });

        jButtonzimmer.setBackground(new java.awt.Color(91, 142, 206));
        jButtonzimmer.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButtonzimmer.setForeground(new java.awt.Color(222, 238, 248));
        jButtonzimmer.setText("Zimmer");
        jButtonzimmer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jButtonzimmer.setPreferredSize(new java.awt.Dimension(128, 28));
        jButtonzimmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonzimmerActionPerformed(evt);
            }
        });

        jButtonkunde.setBackground(new java.awt.Color(91, 142, 206));
        jButtonkunde.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButtonkunde.setForeground(new java.awt.Color(222, 238, 248));
        jButtonkunde.setText("Kunde");
        jButtonkunde.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        jButtonkunde.setPreferredSize(new java.awt.Dimension(128, 28));

        jButtonbuchung.setBackground(new java.awt.Color(91, 142, 206));
        jButtonbuchung.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButtonbuchung.setForeground(new java.awt.Color(222, 238, 248));
        jButtonbuchung.setText("Buchung");
        jButtonbuchung.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jButtonbuchung.setPreferredSize(new java.awt.Dimension(128, 28));
        jButtonbuchung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbuchungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButtonzimmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButtonkunde, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButtonregistrierung)
                .addGap(51, 51, 51)
                .addComponent(jButtonbuchung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonregistrierung)
                    .addComponent(jButtonzimmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonkunde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonbuchung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(222, 238, 248));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(91, 142, 206));
        jLabel4.setText("Geburtstag");

        jLabel5.setBackground(new java.awt.Color(222, 238, 248));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(91, 142, 206));
        jLabel5.setText("Nachname");

        jLabel6.setBackground(new java.awt.Color(222, 238, 248));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(91, 142, 206));
        jLabel6.setText("Vorname");

        jLabel7.setBackground(new java.awt.Color(222, 238, 248));
        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(91, 142, 206));
        jLabel7.setText("Wohnort");

        jLabel8.setBackground(new java.awt.Color(222, 238, 248));
        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(91, 142, 206));
        jLabel8.setText("Postleitzahl");

        jRadioButton2.setBackground(new java.awt.Color(222, 238, 248));
        jRadioButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(91, 142, 206));
        jRadioButton2.setText("Registrierter Kunde");

        jkundennachname.setBackground(new java.awt.Color(222, 238, 248));
        jkundennachname.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jkundennachname.setForeground(new java.awt.Color(91, 142, 206));
        jkundennachname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkundennachnameActionPerformed(evt);
            }
        });

        jkundenvorname.setBackground(new java.awt.Color(222, 238, 248));
        jkundenvorname.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jkundenvorname.setForeground(new java.awt.Color(91, 142, 206));
        jkundenvorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkundenvornameActionPerformed(evt);
            }
        });

        jkundenwohnort.setBackground(new java.awt.Color(222, 238, 248));
        jkundenwohnort.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jkundenwohnort.setForeground(new java.awt.Color(91, 142, 206));
        jkundenwohnort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkundenwohnortActionPerformed(evt);
            }
        });

        jkundenpostleitzahl.setBackground(new java.awt.Color(222, 238, 248));
        jkundenpostleitzahl.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jkundenpostleitzahl.setForeground(new java.awt.Color(91, 142, 206));
        jkundenpostleitzahl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkundenpostleitzahlActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(222, 238, 248));
        jRadioButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(91, 142, 206));
        jRadioButton3.setText("Neuer Kunde");

        jLabel9.setBackground(new java.awt.Color(222, 238, 248));
        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(91, 142, 206));
        jLabel9.setText("Kunden-ID");

        jkundenvornam1.setBackground(new java.awt.Color(222, 238, 248));
        jkundenvornam1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jkundenvornam1.setForeground(new java.awt.Color(91, 142, 206));
        jkundenvornam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkundenvornam1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(222, 238, 248));
        jButton5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(91, 142, 206));
        jButton5.setText("Speichern");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(91, 142, 206), 2, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButtonloeschen.setBackground(new java.awt.Color(222, 238, 248));
        jButtonloeschen.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButtonloeschen.setForeground(new java.awt.Color(91, 142, 206));
        jButtonloeschen.setText("Löschen");
        jButtonloeschen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(91, 142, 206), 2, true));
        jButtonloeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloeschenActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButton2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jkundenvorname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jkundenwohnort, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                            .addComponent(jkundenpostleitzahl, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                            .addComponent(jkundennachname)))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jkundenvornam1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(58, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonloeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(37, 37, 37))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jkundenvorname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jkundennachname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jkundenvornam1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jkundenwohnort, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jkundenpostleitzahl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jButton5)
                    .addComponent(jButtonloeschen))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonregistrierungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregistrierungActionPerformed
         Kundenregistrierung refGui = new Kundenregistrierung();
        refGui.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonregistrierungActionPerformed

    private void jButtonbuchungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbuchungActionPerformed
         Buchungsabschluss refGui = new Buchungsabschluss();
       refGui.setVisible(true);
       this.setVisible(false);

    }//GEN-LAST:event_jButtonbuchungActionPerformed

    private void jkundennachnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkundennachnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkundennachnameActionPerformed

    private void jkundenvornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkundenvornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkundenvornameActionPerformed

    private void jkundenwohnortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkundenwohnortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkundenwohnortActionPerformed

    private void jkundenpostleitzahlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkundenpostleitzahlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkundenpostleitzahlActionPerformed

    private void jkundenvornam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkundenvornam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkundenvornam1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     String vorname = jkundenvorname.getText();
     String name = jkundennachname.getText();
     int plz = Integer.parseInt(jkundenpostleitzahl.getText());
     String wohnort = jkundenwohnort.getText();   
     
     int k = checkupDaten();
     if (k > 0){
         try{
            Kunde refKunde = new Kunde(vorname, name, wohnort, plz);
            Steuerung refSteuerung = Steuerung.getSteuerung();
            refSteuerung.addKunde(refKunde);
         }catch(Exception e){
         jkundenvorname.setText("");
        jkundennachname.setText("");
        jkundenwohnort.setText("");
        jkundenpostleitzahl.setText("");
         }
     }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonloeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloeschenActionPerformed
        jkundenvorname.setText("");
        jkundennachname.setText("");
        jkundenwohnort.setText("");
        jkundenpostleitzahl.setText("");
    }//GEN-LAST:event_jButtonloeschenActionPerformed

    private void jButtonzimmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonzimmerActionPerformed
        zimmer_auswahl refGui = new zimmer_auswahl();
        refGui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonzimmerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kunden_daten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kunden_daten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kunden_daten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kunden_daten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kunden_daten().setVisible(true);
            }
        });
    }
        public int checkupDaten() {
        String vn = jkundenvorname.getText();
        String nn = jkundennachname.getText();
        String ort = jkundenwohnort.getText();
        //int plz = Integer.parseInt(jkundenpostleitzahl.getText());
        if (vn.length() < 2 || nn.length() < 2 || ort.length() < 2) {
            new javax.swing.JOptionPane().showMessageDialog(this,
                    "Vor- bzw. Nachname oder Ort fehlerhaft",
                    "Bitte korrigieren",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return 0;
        }else; 
            return 1;
        }
                
        

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonbuchung;
    private javax.swing.JButton jButtonkunde;
    private javax.swing.JButton jButtonloeschen;
    private javax.swing.JButton jButtonregistrierung;
    private javax.swing.JButton jButtonzimmer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jkundennachname;
    private javax.swing.JTextField jkundenpostleitzahl;
    private javax.swing.JTextField jkundenvornam1;
    private javax.swing.JTextField jkundenvorname;
    private javax.swing.JTextField jkundenwohnort;
    // End of variables declaration//GEN-END:variables
}
