/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_eigen;

import java.util.Date;

/**
 *
 * @author johan
 */
public class Kundenregistrierung extends javax.swing.JFrame {

    /**
     * Creates new form Kundenregistrierung
     */
    public Kundenregistrierung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonzimmer = new javax.swing.JButton();
        jButtonkunde = new javax.swing.JButton();
        buchung = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jkundenemail = new javax.swing.JTextField();
        jkundenid = new javax.swing.JTextField();
        jspinnergeburtstag = new javax.swing.JSpinner();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jChecknewsletter = new javax.swing.JCheckBox();
        jCheckBoxdsvgo = new javax.swing.JCheckBox();
        jCheckBoxumfrage = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(222, 238, 248));
        jPanel1.setEnabled(false);

        jPanel2.setBackground(new java.awt.Color(91, 142, 206));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(91, 142, 206));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Hier könnte schon \nbald ihre \nFunktionalität \nentstehen...");
        jTextArea1.setMaximumSize(new java.awt.Dimension(90, 88));
        jTextArea1.setMinimumSize(new java.awt.Dimension(90, 88));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );

        jPanel4.setBackground(new java.awt.Color(91, 142, 206));

        jLabel1.setBackground(new java.awt.Color(222, 238, 206));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 238, 248));
        jLabel1.setText("Registrierung des Neu-Kundens");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 192, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(91, 142, 206));

        jButton1.setBackground(new java.awt.Color(91, 142, 206));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(222, 238, 248));
        jButton1.setText("Registrierung");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonzimmer.setBackground(new java.awt.Color(91, 142, 206));
        jButtonzimmer.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButtonzimmer.setForeground(new java.awt.Color(222, 238, 248));
        jButtonzimmer.setText("Zimmer");
        jButtonzimmer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jButtonzimmer.setPreferredSize(new java.awt.Dimension(128, 28));
        jButtonzimmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonzimmerActionPerformed(evt);
            }
        });

        jButtonkunde.setBackground(new java.awt.Color(91, 142, 206));
        jButtonkunde.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButtonkunde.setForeground(new java.awt.Color(222, 238, 248));
        jButtonkunde.setText("Kunde");
        jButtonkunde.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jButtonkunde.setPreferredSize(new java.awt.Dimension(128, 28));
        jButtonkunde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonkundeActionPerformed(evt);
            }
        });

        buchung.setBackground(new java.awt.Color(91, 142, 206));
        buchung.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        buchung.setForeground(new java.awt.Color(222, 238, 248));
        buchung.setText("Buchung");
        buchung.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        buchung.setPreferredSize(new java.awt.Dimension(128, 28));
        buchung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buchungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButtonzimmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButtonkunde, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addGap(51, 51, 51)
                .addComponent(buchung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonzimmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonkunde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buchung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(222, 238, 248));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(91, 142, 206));
        jLabel4.setText("Erstbesuch");

        jLabel5.setBackground(new java.awt.Color(222, 238, 248));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(91, 142, 206));
        jLabel5.setText("E-Mail");

        jLabel6.setBackground(new java.awt.Color(222, 238, 248));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(91, 142, 206));
        jLabel6.setText("Kunden-ID");

        jkundenemail.setBackground(new java.awt.Color(222, 238, 248));
        jkundenemail.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jkundenemail.setForeground(new java.awt.Color(91, 142, 206));
        jkundenemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkundenemailActionPerformed(evt);
            }
        });

        jkundenid.setBackground(new java.awt.Color(222, 238, 248));
        jkundenid.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jkundenid.setForeground(new java.awt.Color(91, 142, 206));
        jkundenid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkundenidActionPerformed(evt);
            }
        });

        jspinnergeburtstag.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jspinnergeburtstag.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1703788234644L), new java.util.Date(), java.util.Calendar.MONTH));

        jButton6.setBackground(new java.awt.Color(222, 238, 248));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(91, 142, 206));
        jButton6.setText("Zurück");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(91, 142, 206), 2, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(222, 238, 248));
        jButton5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(91, 142, 206));
        jButton5.setText("Speichern");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(91, 142, 206), 2, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jChecknewsletter.setBackground(new java.awt.Color(222, 238, 248));
        jChecknewsletter.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jChecknewsletter.setForeground(new java.awt.Color(91, 142, 206));
        jChecknewsletter.setText("Newsletter-Anmeldung");
        jChecknewsletter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChecknewsletterActionPerformed(evt);
            }
        });

        jCheckBoxdsvgo.setBackground(new java.awt.Color(222, 238, 248));
        jCheckBoxdsvgo.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jCheckBoxdsvgo.setForeground(new java.awt.Color(91, 142, 206));
        jCheckBoxdsvgo.setText("Einverständnis Datenschutz (DSVGO)");
        jCheckBoxdsvgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxdsvgoActionPerformed(evt);
            }
        });

        jCheckBoxumfrage.setBackground(new java.awt.Color(222, 238, 248));
        jCheckBoxumfrage.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jCheckBoxumfrage.setForeground(new java.awt.Color(91, 142, 206));
        jCheckBoxumfrage.setText("Einverständnis zur Teilnahme an Zufriedenheits-Umfrage");
        jCheckBoxumfrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxumfrageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jChecknewsletter, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBoxdsvgo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBoxumfrage, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jkundenid, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                        .addComponent(jkundenemail)
                                        .addComponent(jspinnergeburtstag))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5)
                                        .addGap(57, 57, 57))))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jkundenid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jkundenemail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jspinnergeburtstag, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jChecknewsletter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxdsvgo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxumfrage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(97, 97, 97))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buchungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buchungActionPerformed
        
    Buchungsabschluss refGui = new Buchungsabschluss();
       refGui.setVisible(true);
       this.setVisible(false);

    }//GEN-LAST:event_buchungActionPerformed

    private void jkundenemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkundenemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkundenemailActionPerformed

    private void jkundenidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkundenidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkundenidActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jChecknewsletter.setText("");
        jkundenid.setText("");
        jkundenemail.setText("");
        jCheckBoxdsvgo.setText("");
        jCheckBoxumfrage.setText("");
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int kunden_id = Integer.parseInt(jkundenid.getText());
        String email = jkundenemail.getText();
        //Date erstbesuch = Date.parse(jspinnergeburtstag.getText());
        boolean newsletter = Boolean.parseBoolean(jChecknewsletter.getText());
        boolean dsvgo = Boolean.parseBoolean(jCheckBoxdsvgo.getText());
        boolean umfrage = Boolean.parseBoolean(jCheckBoxumfrage.getText());
        
        Registriert refReg = new Registriert(email, newsletter, dsvgo, umfrage);
        
        Steuerung refSteuerung = Steuerung.getSteuerung();
        refSteuerung.addRegistriert(refReg);
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jChecknewsletterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChecknewsletterActionPerformed
        
    }//GEN-LAST:event_jChecknewsletterActionPerformed

    private void jCheckBoxdsvgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxdsvgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxdsvgoActionPerformed

    private void jCheckBoxumfrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxumfrageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxumfrageActionPerformed

    private void jButtonkundeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonkundeActionPerformed
       kunden_daten refGui = new kunden_daten();
        refGui.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonkundeActionPerformed

    private void jButtonzimmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonzimmerActionPerformed
        zimmer_auswahl refGui = new zimmer_auswahl();
        refGui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonzimmerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kundenregistrierung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kundenregistrierung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kundenregistrierung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kundenregistrierung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kundenregistrierung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buchung;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonkunde;
    private javax.swing.JButton jButtonzimmer;
    private javax.swing.JCheckBox jCheckBoxdsvgo;
    private javax.swing.JCheckBox jCheckBoxumfrage;
    private javax.swing.JCheckBox jChecknewsletter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jkundenemail;
    private javax.swing.JTextField jkundenid;
    private javax.swing.JSpinner jspinnergeburtstag;
    // End of variables declaration//GEN-END:variables
}
